# Bài 1. Tạo Tensor cơ bản

In [1]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


### yêu cầu

In [2]:
print(a.shape)
print(a.ndim)
print(a.dtype)

torch.Size([2, 3])
2
torch.int32


# Bài 2. Tạo các Tensor thường dùng

In [ ]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.7775, 0.6722, 0.2647, 0.4145],
        [0.5770, 0.5275, 0.0355, 0.7978],
        [0.1758, 0.2452, 0.9329, 0.8235]])
tensor([[-0.2972, -1.8080, -0.4255, -1.2812],
        [ 0.9214, -0.3788,  1.7884, -0.7857],
        [-1.0471,  1.3513, -0.3444, -0.2707]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


### yêu cầu

#### rand chỉ ngẫu nhiên số dương
#### randn bao gồm ngẫu nhiên số dương và âm

# Bài 3. Kiểm tra thông tin Tensor


In [3]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


### yêu cầu

# Bài 4. Slicing và Indexing

In [4]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 2.1584, -1.1460, -0.0414, -0.4172, -0.4737],
         [-0.6707,  0.8514, -0.2601,  0.8226,  1.7799],
         [-0.2881, -0.0577, -0.2506, -0.3744, -0.3896],
         [ 2.3631, -0.7755, -0.6719,  1.6252, -0.7045]],

        [[-1.0906,  1.3231, -0.8657,  0.5738, -0.8420],
         [-0.8198,  0.7970, -0.1963, -1.2632,  1.5800],
         [-0.3613, -1.3732,  0.4799, -0.3999, -1.6599],
         [-0.0282, -0.7034, -0.2265,  2.0430, -0.4954]],

        [[-0.8845,  0.6596, -1.5537,  1.2679, -0.5042],
         [-1.0902, -0.0293, -0.7058,  0.1616,  0.1242],
         [ 0.0938, -0.0666, -0.4159, -1.4869,  0.2699],
         [-0.7269,  0.1576, -1.2187,  0.9829, -0.4997]]])

Tensor a[1]:
tensor([[-1.0906,  1.3231, -0.8657,  0.5738, -0.8420],
        [-0.8198,  0.7970, -0.1963, -1.2632,  1.5800],
        [-0.3613, -1.3732,  0.4799, -0.3999, -1.6599],
        [-0.0282, -0.7034, -0.2265,  2.0430, -0.4954]])

Tensor a[1:, 2:4]:
tensor([[[-0.3613, -1.3732,  0.4799, -0.3999, -1.6

### yêu cầu

# Bài 5. Reshape và Flatten

In [5]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 0.3880, -1.1141,  1.1398,  0.7788],
        [ 0.5542,  1.1509, -1.0772, -1.0040],
        [-0.8241, -0.0035, -0.4169,  0.4017]])

Flatten:
tensor([ 0.3880, -1.1141,  1.1398,  0.7788,  0.5542,  1.1509, -1.0772, -1.0040,
        -0.8241, -0.0035, -0.4169,  0.4017])

Reshape to 3 x 2 x 2:
tensor([[[ 0.3880, -1.1141],
         [ 1.1398,  0.7788]],

        [[ 0.5542,  1.1509],
         [-1.0772, -1.0040]],

        [[-0.8241, -0.0035],
         [-0.4169,  0.4017]]])


### yêu cầu

# Bài 6. Phép toán và nhân ma trận

In [6]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-3.2135,  0.1077,  0.6072],
        [-0.2731, -0.0344, -0.5868]])
b:
tensor([[-1.5710,  2.0872,  0.4583],
        [-0.5400,  2.2987, -0.8522]])

a + b:
tensor([[-4.7845,  2.1949,  1.0655],
        [-0.8132,  2.2644, -1.4391]])

a / b:
tensor([[ 2.0455,  0.0516,  1.3248],
        [ 0.5058, -0.0150,  0.6885]])

a^2:
tensor([[1.0327e+01, 1.1598e-02, 3.6867e-01],
        [7.4604e-02, 1.1815e-03, 3.4435e-01]])

Matrix multiplication:
tensor([[5.5515, 1.4655],
        [0.0884, 0.5686]])


### yêu cầu

# Bài 7. Các hàm thống kê trên Tensor

In [7]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-0.6182,  0.4732,  0.3136, -2.1748],
        [-0.8707, -0.1144,  1.5050, -1.7080],
        [ 0.2840,  0.1443, -0.3403,  0.3415]])

Mean:
tensor([-0.4017,  0.1677,  0.4928, -1.1804])

Standard deviation:
tensor([0.6071, 0.2945, 0.9356, 1.3386])

Cumulative sum:
tensor([[-0.6182,  0.4732,  0.3136, -2.1748],
        [-1.4890,  0.3588,  1.8186, -3.8828],
        [-1.2050,  0.5031,  1.4784, -3.5413]])


### yêu cầu

# Bài 8. Autograd cơ bản

In [8]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


### yêu cầu

# Bài 9. Gradient Descent tìm hệ số đa thức

In [10]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 0.8217],
        [-0.2504],
        [-2.2315]], requires_grad=True)
Learned coefficients:
tensor([[1.0095],
        [1.9962],
        [2.3624]], requires_grad=True)


# Bài 10. Giải hệ phương trình bằng Autograd

In [12]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.8061, requires_grad=True)
B = tensor(4.1938, requires_grad=True)
C = tensor(3.1939, requires_grad=True)
D = tensor(2.1939, requires_grad=True)


# Bài 11. Ôn tập PyTorch và Autograd

In [13]:
import torch

X = torch.arange(1, 25)

X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("X =", X)
print("X reshape 4 x 6:\n", X_4x6)
print("X reshape 2 x 12:\n", X_2x12)
print("X reshape 2 x 3 x 4:\n", X_2x3x4)

X = tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])
X reshape 4 x 6:
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])
X reshape 2 x 12:
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
X reshape 2 x 3 x 4:
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


In [14]:
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("A =\n", A)
print("B =\n", B)
print("A + B =\n", A + B)
print("A * B =\n", A * B)
print("A / B =\n", A / B)
print("Trung bình theo cột =", A.mean(dim=0))
print("Độ lệch chuẩn theo cột =", A.std(dim=0))

A =
 tensor([[ 0.0752, -1.1424, -0.2482,  0.7398],
        [-0.5443, -0.4147,  0.1445,  0.3091],
        [-0.6976, -0.9979,  0.4560,  0.7389]])
B =
 tensor([[-1.8488, -1.3071, -0.4847, -0.2552],
        [ 0.5615,  0.7687, -1.0001,  1.0459],
        [-0.0038,  0.3630,  2.0591,  0.8867]])
A + B =
 tensor([[-1.7736, -2.4495, -0.7329,  0.4845],
        [ 0.0173,  0.3540, -0.8556,  1.3550],
        [-0.7014, -0.6349,  2.5151,  1.6256]])
A * B =
 tensor([[-0.1390,  1.4932,  0.1203, -0.1888],
        [-0.3056, -0.3188, -0.1445,  0.3233],
        [ 0.0026, -0.3622,  0.9390,  0.6552]])
A / B =
 tensor([[-4.0662e-02,  8.7395e-01,  5.1202e-01, -2.8983e+00],
        [-9.6920e-01, -5.3949e-01, -1.4448e-01,  2.9559e-01],
        [ 1.8423e+02, -2.7492e+00,  2.2148e-01,  8.3334e-01]])
Trung bình theo cột = tensor([-0.3889, -0.8517,  0.1175,  0.5959])
Độ lệch chuẩn theo cột = tensor([0.4091, 0.3852, 0.3529, 0.2484])


In [15]:
x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()

dy_dx_thu_cong = 4 * 2 + 5

print("y =", y.item())
print("dy/dx bằng autograd =", x.grad.item())
print("dy/dx thủ công =", dy_dx_thu_cong)
print("Kết quả khớp:", torch.isclose(x.grad, torch.tensor(float(dy_dx_thu_cong))).item())

y = 21.0
dy/dx bằng autograd = 13.0
dy/dx thủ công = 13
Kết quả khớp: True


In [17]:
import numpy as np

polynomial = np.poly1d([2, -3, 5])
N = 100
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([X * X, X, np.ones_like(X)])

w = torch.randn(3, 1, requires_grad=True)
features = torch.tensor(XX, dtype=torch.float32)
targets = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)

for _ in range(10000):
    optimizer.zero_grad()
    prediction = features @ w
    mse = torch.mean((targets - prediction) ** 2)
    mse.backward()
    optimizer.step()

print("Hệ số tìm được [x^2, x, hằng số] =", w.detach().flatten())
print("Hệ số mong đợi [2, -3, 5] =", torch.tensor([2.0, -3.0, 5.0]))
print("MSE cuối =", mse.item())

Hệ số tìm được [x^2, x, hằng số] = tensor([ 2.0000, -3.0000,  5.0000])
Hệ số mong đợi [2, -3, 5] = tensor([ 2., -3.,  5.])
MSE cuối = 1.932505717949784e-11
