# Bài 1. Tạo Tensor cơ bản

In [31]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


### yêu cầu

In [32]:
print(a.shape)
print(a.ndim)
print(a.dtype)

torch.Size([2, 3])
2
torch.int32


# Bài 2. Tạo các Tensor thường dùng

In [33]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.4018, 0.1864, 0.0372, 0.8008],
        [0.3778, 0.9037, 0.3562, 0.3641],
        [0.0224, 0.2916, 0.4471, 0.5936]])
tensor([[-0.7403, -1.1701,  1.3139, -0.5192],
        [-1.0062,  0.3501,  0.6560, -0.5244],
        [-0.7568,  0.6951, -0.3055,  1.2866]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


### yêu cầu

Tạo thêm một Tensor có kích thước `5 × 5`, trong đó tất cả các phần tử đều có giá trị `10`.

In [34]:
tensor_5x5 = torch.full((5, 5), 10)
print(tensor_5x5)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


#### Hàm rand tạo số ngẫu nhiên trong khoảng [0, 1). Hàm randn tạo số ngẫu nhiên theo phân phối chuẩn nên có thể xuất hiện cả số âm và số dương

# Bài 3. Kiểm tra thông tin Tensor


In [53]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


### yêu cầu

**Giải thích:** `torch.Size([2, 3, 4])` cho biết tensor có 3 chiều với kích thước lần lượt là 2, 3 và 4. Nghĩa là tensor gồm 2 khối, mỗi khối có 3 hàng và mỗi hàng có 4 phần tử. Tổng số phần tử là `2 × 3 × 4 = 24`.

# Bài 4. Slicing và Indexing

In [57]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 1.0658, -0.9496,  0.8519,  0.5298,  0.6851],
         [-0.6662,  0.2649,  0.0822,  1.3220, -0.1275],
         [-0.3102,  0.3771,  0.0367, -0.1612, -2.2314],
         [-0.4768,  0.3715, -1.3547,  1.7833,  0.1129]],

        [[ 1.1653,  1.2053,  0.6787,  0.5027, -0.7947],
         [ 0.2719, -0.5481, -0.5425,  2.2760,  0.2422],
         [-0.3571,  0.3639, -0.1884, -0.2844,  0.6406],
         [ 2.0354, -0.9249,  0.2360, -0.6652,  0.5867]],

        [[-0.5118, -0.7820, -1.0686,  0.1552,  1.3896],
         [-0.3809, -1.2834,  0.2534,  0.7147, -0.1241],
         [ 0.0579, -0.3212, -1.6044, -0.2322,  0.2467],
         [-0.7191,  0.7285,  0.5995,  1.4337,  1.5465]]])

Tensor a[1]:
tensor([[ 1.1653,  1.2053,  0.6787,  0.5027, -0.7947],
        [ 0.2719, -0.5481, -0.5425,  2.2760,  0.2422],
        [-0.3571,  0.3639, -0.1884, -0.2844,  0.6406],
        [ 2.0354, -0.9249,  0.2360, -0.6652,  0.5867]])

Tensor a[1:, 2:4]:
tensor([[[-0.3571,  0.3639, -0.1884, -0.2844,  0.6

### yêu cầu

#### Cho biết shape của a[1] và a[1:, 2:4].
#### Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

In [59]:

print("Shape của a[1]:", a[1].shape)
print("Shape của a[1:, 2:4]:", a[1:, 2:4].shape)

hai_phan_tu_cuoi = a[:, :, -2:]
print("Hai phần tử cuối trên chiều thứ ba:")
print(hai_phan_tu_cuoi)
print("Shape:", hai_phan_tu_cuoi.shape)

Shape của a[1]: torch.Size([4, 5])
Shape của a[1:, 2:4]: torch.Size([2, 2, 5])
Hai phần tử cuối trên chiều thứ ba:
tensor([[[ 0.5298,  0.6851],
         [ 1.3220, -0.1275],
         [-0.1612, -2.2314],
         [ 1.7833,  0.1129]],

        [[ 0.5027, -0.7947],
         [ 2.2760,  0.2422],
         [-0.2844,  0.6406],
         [-0.6652,  0.5867]],

        [[ 0.1552,  1.3896],
         [ 0.7147, -0.1241],
         [-0.2322,  0.2467],
         [ 1.4337,  1.5465]]])
Shape: torch.Size([3, 4, 2])


# Bài 5. Reshape và Flatten

In [62]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-1.6715,  1.2223,  0.3359,  0.2382],
        [-0.8302, -1.4353, -1.6430, -1.4084],
        [-0.2441,  1.8096, -0.7811, -0.5218]])

Flatten:
tensor([-1.6715,  1.2223,  0.3359,  0.2382, -0.8302, -1.4353, -1.6430, -1.4084,
        -0.2441,  1.8096, -0.7811, -0.5218])

Reshape to 3 x 2 x 2:
tensor([[[-1.6715,  1.2223],
         [ 0.3359,  0.2382]],

        [[-0.8302, -1.4353],
         [-1.6430, -1.4084]],

        [[-0.2441,  1.8096],
         [-0.7811, -0.5218]]])


### yêu cầu

#### Kiểm tra số phần tử trước và sau khi reshape.
#### Thử reshape Tensor thành kích thước 2 × 6.

In [63]:
so_phan_tu_truoc = a.numel()
a_2x6 = a.reshape(2, 6)
so_phan_tu_sau = a_2x6.numel()

print("Số phần tử trước khi reshape:", so_phan_tu_truoc)
print("Tensor sau khi reshape thành 2 x 6:")
print(a_2x6)
print("Shape sau khi reshape:", a_2x6.shape)
print("Số phần tử sau khi reshape:", so_phan_tu_sau)
print("Số phần tử không thay đổi:", so_phan_tu_truoc == so_phan_tu_sau)

Số phần tử trước khi reshape: 12
Tensor sau khi reshape thành 2 x 6:
tensor([[-1.6715,  1.2223,  0.3359,  0.2382, -0.8302, -1.4353],
        [-1.6430, -1.4084, -0.2441,  1.8096, -0.7811, -0.5218]])
Shape sau khi reshape: torch.Size([2, 6])
Số phần tử sau khi reshape: 12
Số phần tử không thay đổi: True


# Bài 6. Phép toán và nhân ma trận

In [67]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-0.2147, -1.1422,  0.7721],
        [ 1.4436, -0.2644,  1.4040]])
b:
tensor([[-0.4864, -1.5258,  1.5885],
        [ 1.4904,  1.0377, -0.3371]])

a + b:
tensor([[-0.7011, -2.6679,  2.3606],
        [ 2.9340,  0.7733,  1.0669]])

a / b:
tensor([[ 0.4413,  0.7486,  0.4861],
        [ 0.9686, -0.2548, -4.1650]])

a^2:
tensor([[0.0461, 1.3045, 0.5961],
        [2.0841, 0.0699, 1.9712]])

Matrix multiplication:
tensor([[ 3.0736, -1.7655],
        [ 1.9314,  1.4039]])


### yêu cầu

#### Phân biệt phép toán a * b với a @ b.T.
#### Cho biết shape của kết quả a @ b.T.

In [69]:


print("a * b là phép nhân theo từng phần tử:")
print(a * b)

print("\na @ b.T là phép nhân ma trận:")
ket_qua_nhan_ma_tran = a @ b.T
print(ket_qua_nhan_ma_tran)
print("Shape của a @ b.T:", ket_qua_nhan_ma_tran.shape)

print("\nKết luận: a * b có shape", (a * b).shape,
      "còn a @ b.T có shape", ket_qua_nhan_ma_tran.shape)

a * b là phép nhân theo từng phần tử:
tensor([[ 0.1575, -2.8001, -0.5631],
        [-3.7546, -0.0304,  0.4081]])

a @ b.T là phép nhân ma trận:
tensor([[-3.2057,  1.3085],
        [ 0.2298, -3.3769]])
Shape của a @ b.T: torch.Size([2, 2])

Kết luận: a * b có shape torch.Size([2, 3]) còn a @ b.T có shape torch.Size([2, 2])


# Bài 7. Các hàm thống kê trên Tensor

In [41]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-1.6058,  0.9779, -0.4268,  3.2749],
        [-1.7034,  0.8336,  0.7409, -0.2640],
        [-1.8750,  0.3033, -0.7123, -1.2699]])

Mean:
tensor([-1.7281,  0.7049, -0.1327,  0.5803])

Standard deviation:
tensor([0.1363, 0.3552, 0.7699, 2.3872])

Cumulative sum:
tensor([[-1.6058,  0.9779, -0.4268,  3.2749],
        [-3.3092,  1.8115,  0.3141,  3.0110],
        [-5.1842,  2.1148, -0.3982,  1.7410]])


### yêu cầu

#### Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.

In [ ]:
a = torch.randn(3, 4)

print("Tensor a:")
print(a)

mean_dim1 = torch.mean(a, dim=1)
std_dim1 = torch.std(a, dim=1)
cumsum_dim1 = torch.cumsum(a, dim=1)

print("\nMean theo dim=1:")
print(mean_dim1)
print("Shape:", mean_dim1.shape)

print("\nStandard deviation theo dim=1:")
print(std_dim1)
print("Shape:", std_dim1.shape)

print("\nCumulative sum theo dim=1:")
print(cumsum_dim1)
print("Shape:", cumsum_dim1.shape)

Tensor a:
tensor([[-0.2093,  0.0874, -0.1305, -0.6590],
        [ 0.4515, -1.5541,  0.1181, -2.8172],
        [ 0.4430, -0.0042,  0.7517,  0.6313]])

Mean theo dim=1:
tensor([-0.2278, -0.9504,  0.4555])
Shape: torch.Size([3])

Standard deviation theo dim=1:
tensor([0.3136, 1.5227, 0.3317])
Shape: torch.Size([3])

Cumulative sum theo dim=1:
tensor([[-0.2093, -0.1219, -0.2523, -0.9113],
        [ 0.4515, -1.1027, -0.9845, -3.8017],
        [ 0.4430,  0.4388,  1.1905,  1.8219]])
Shape: torch.Size([3, 4])


**Nhận xét:** Khi dùng `dim=0`, các phép tính được thực hiện theo từng cột nên `mean` và `std` trả về 4 giá trị. Khi dùng `dim=1`, các phép tính được thực hiện theo từng hàng nên `mean` và `std` trả về 3 giá trị. `cumsum(dim=1)` tính tổng tích lũy từ trái sang phải trong từng hàng và vẫn giữ nguyên shape `(3, 4)`.

# Bài 8. Autograd cơ bản

In [65]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


### yêu cầu

#### Tính thủ công đạo hàm của y = x2 tại x = 3.6 và so sánh với x.grad.
#### Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.

In [66]:
x = torch.tensor(3.6, requires_grad=True)
y = x ** 2
y.backward()

gradient_thu_cong_1 = 2 * 3.6
print("Hàm y = x^2")
print("Gradient bằng Autograd:", x.grad.item())
print("Gradient tính thủ công:", gradient_thu_cong_1)
print("Kết quả khớp:", torch.isclose(x.grad, torch.tensor(gradient_thu_cong_1)).item())

x_moi = torch.tensor(3.6, requires_grad=True)
y_moi = 3 * x_moi ** 2 + 2 * x_moi + 1
y_moi.backward()

gradient_thu_cong_2 = 6 * 3.6 + 2
print("\nHàm y = 3*x^2 + 2*x + 1")
print("Gradient bằng Autograd:", x_moi.grad.item())
print("Gradient tính thủ công:", gradient_thu_cong_2)
print("Kết quả khớp:", torch.isclose(x_moi.grad, torch.tensor(gradient_thu_cong_2)).item())

Hàm y = x^2
Gradient bằng Autograd: 7.199999809265137
Gradient tính thủ công: 7.2
Kết quả khớp: True

Hàm y = 3*x^2 + 2*x + 1
Gradient bằng Autograd: 23.599998474121094
Gradient tính thủ công: 23.6
Kết quả khớp: True


# Bài 9. Gradient Descent tìm hệ số đa thức

In [45]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[0.4275],
        [0.3787],
        [0.8405]], requires_grad=True)


Learned coefficients:
tensor([[1.0195],
        [1.8616],
        [2.2449]], requires_grad=True)


### yêu cầu

#### So sánh ba hệ số học được với [1, 2, 3].
#### Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().

In [46]:
he_so_hoc_duoc = w.detach().flatten()
he_so_mong_doi = torch.tensor([1.0, 2.0, 3.0])
sai_so = he_so_hoc_duoc - he_so_mong_doi

print("Ba hệ số học được [x^2, x, hằng số] =", he_so_hoc_duoc)
print("Ba hệ số mong đợi =", he_so_mong_doi)
print("Sai số từng hệ số =", sai_so)
print("Sai số tuyệt đối trung bình =", torch.mean(torch.abs(sai_so)).item())

Ba hệ số học được [x^2, x, hằng số] = tensor([1.0195, 1.8616, 2.2449])
Ba hệ số mong đợi = tensor([1., 2., 3.])
Sai số từng hệ số = tensor([ 0.0195, -0.1384, -0.7551])
Sai số tuyệt đối trung bình = 0.3043486773967743


# Bài 10. Giải hệ phương trình bằng Autograd

In [51]:
import random
import torch
A_bai10 = torch.tensor(random.random(), requires_grad=True)
B_bai10 = torch.tensor(random.random(), requires_grad=True)
C_bai10 = torch.tensor(random.random(), requires_grad=True)
D_bai10 = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A_bai10, B_bai10, C_bai10, D_bai10], lr=0.01)
for _ in range(EPOCHS):
    y1 = A_bai10 + B_bai10 - 9
    y2 = C_bai10 - D_bai10 - 1
    y3 = A_bai10 + C_bai10 - 8
    y4 = B_bai10 - D_bai10 - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A_bai10)
print("B =", B_bai10)
print("C =", C_bai10)
print("D =", D_bai10)

A = tensor(4.1857, requires_grad=True)
B = tensor(4.8142, requires_grad=True)
C = tensor(3.8143, requires_grad=True)
D = tensor(2.8142, requires_grad=True)


### yêu cầu

#### Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.
#### Nhận xét vì sao bài toán có thể có nhiều nghiệm.

In [52]:
A_value = A_bai10.detach().item()
B_value = B_bai10.detach().item()
C_value = C_bai10.detach().item()
D_value = D_bai10.detach().item()

residuals = {
    "A + B - 9": A_value + B_value - 9,
    "C - D - 1": C_value - D_value - 1,
    "A + C - 8": A_value + C_value - 8,
    "B - D - 2": B_value - D_value - 2,
}

print("Sai số của bốn phương trình:")
for equation, residual in residuals.items():
    print(f"{equation} = {residual:.6f}")

print("\nNghiệm tổng quát với t = D:")
print("A = 7 - t")
print("B = t + 2")
print("C = t + 1")
print("D = t")

for t in [0.0, 1.0, 2.0]:
    solution = (7 - t, t + 2, t + 1, t)
    print(f"t = {t}: (A, B, C, D) = {solution}")

Sai số của bốn phương trình:
A + B - 9 = -0.000053
C - D - 1 = 0.000020
A + C - 8 = -0.000019
B - D - 2 = -0.000014

Nghiệm tổng quát với t = D:
A = 7 - t
B = t + 2
C = t + 1
D = t
t = 0.0: (A, B, C, D) = (7.0, 2.0, 1.0, 0.0)
t = 1.0: (A, B, C, D) = (6.0, 3.0, 2.0, 1.0)
t = 2.0: (A, B, C, D) = (5.0, 4.0, 3.0, 2.0)


# Bài 11. Ôn tập PyTorch và Autograd

In [ ]:
import torch

X = torch.arange(1, 25)

X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("X =", X)
print("X reshape 4 x 6:\n", X_4x6)
print("X reshape 2 x 12:\n", X_2x12)
print("X reshape 2 x 3 x 4:\n", X_2x3x4)

X = tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])
X reshape 4 x 6:
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])
X reshape 2 x 12:
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
X reshape 2 x 3 x 4:
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


In [ ]:
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("A =\n", A)
print("B =\n", B)
print("A + B =\n", A + B)
print("A * B =\n", A * B)
print("A / B =\n", A / B)
print("Trung bình theo cột =", A.mean(dim=0))
print("Độ lệch chuẩn theo cột =", A.std(dim=0))

A =
 tensor([[ 0.4842,  0.5756,  0.8946, -1.0058],
        [-0.1938, -0.6089,  0.5831, -0.7424],
        [ 0.2982,  0.5908, -0.2844,  0.0369]])
B =
 tensor([[-0.6251, -0.7958, -1.2290, -0.2197],
        [ 0.7818, -1.9273, -0.9188, -0.4764],
        [ 0.4147, -2.2522, -1.0142,  0.9546]])
A + B =
 tensor([[-0.1409, -0.2202, -0.3344, -1.2255],
        [ 0.5880, -2.5362, -0.3357, -1.2188],
        [ 0.7129, -1.6614, -1.2986,  0.9915]])
A * B =
 tensor([[-0.3027, -0.4580, -1.0994,  0.2209],
        [-0.1515,  1.1736, -0.5358,  0.3537],
        [ 0.1237, -1.3306,  0.2884,  0.0352]])
A / B =
 tensor([[-0.7745, -0.7233, -0.7279,  4.5790],
        [-0.2478,  0.3160, -0.6346,  1.5582],
        [ 0.7190, -0.2623,  0.2804,  0.0386]])
Trung bình theo cột = tensor([ 0.1962,  0.1858,  0.3978, -0.5704])
Độ lệch chuẩn theo cột = tensor([0.3503, 0.6883, 0.6109, 0.5422])


In [ ]:
x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()

dy_dx_thu_cong = 4 * 2 + 5

print("y =", y.item())
print("dy/dx bằng autograd =", x.grad.item())
print("dy/dx thủ công =", dy_dx_thu_cong)
print("Kết quả khớp:", torch.isclose(x.grad, torch.tensor(float(dy_dx_thu_cong))).item())

y = 21.0
dy/dx bằng autograd = 13.0
dy/dx thủ công = 13
Kết quả khớp: True


In [ ]:
import numpy as np

polynomial = np.poly1d([2, -3, 5])
N = 100
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([X * X, X, np.ones_like(X)])

w = torch.randn(3, 1, requires_grad=True)
features = torch.tensor(XX, dtype=torch.float32)
targets = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)

for _ in range(10000):
    optimizer.zero_grad()
    prediction = features @ w
    mse = torch.mean((targets - prediction) ** 2)
    mse.backward()
    optimizer.step()

print("Hệ số tìm được [x^2, x, hằng số] =", w.detach().flatten())
print("Hệ số mong đợi [2, -3, 5] =", torch.tensor([2.0, -3.0, 5.0]))
print("MSE cuối =", mse.item())

Hệ số tìm được [x^2, x, hằng số] = tensor([ 2.0000, -3.0000,  5.0000])
Hệ số mong đợi [2, -3, 5] = tensor([ 2., -3.,  5.])
MSE cuối = 1.3980070573405001e-11
